# Generated by Django 4.0 on 2022-04-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=30)),
                ('medicine_per', models.CharField(max_length=30)),
                ('medicine_qunatity', models.CharField(max_length=30)),
                ('medicine_sellingprice', models.CharField(max_length=30)),
            ],
        ),
    ]
