# Generated by Django 4.0 on 2022-04-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='medicine_qunatity',
            field=models.IntegerField(),
        ),
    ]
